# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            d1scr3te delibe rations 
tagline:          A personal blog
description:      non-trivial discretised reflections on a continuous universe. 
description_line2: "&#x5Ba maths student's attempt at literacy&#x5D"
url:              https://muzz-yasir.github.io
baseurl:          ""
future: true

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# pagination:
#   enabled: true
#   debug: false
#   collections: 'posts'
#   per_page: 5
#   paginate_path: '/page/:num/'

plugins: [jekyll-paginate]

paginate: 5

# Custom vars
version:          2.1.0

github:
   repo:           https://github.com/muzz-yasir/

social:
    linkedin: https://www.linkedin.com/in/mustafa-yasir/
    email: mailto:mustafa.y36@gmail.com
